### ISSUE TITLE
智源官网提供的API里的AccessToken如何获得呀？

### ISSUE THREAD

**Issue by wangheng0602** [chuhaojin/WenLan-api-document#1]

**Comment by chuhaojin** [comment]
可以先使用本文档里的API，和官网的完全一致哈。官网的API文档预计明天（或几天内）会重新整理排版解决AccessToken的问题，谢谢您的关注

**Comment by chuhaojin** [comment]
已经update啦

**Comment by wangheng0602** [comment]
您好，我看到官网里的API是有调用次数限制的，而您的API好像没有这个限制，甚至不需要ID和密钥，这是怎么做到的呀？
